In [1]:
import ADCrowdNet
import tensorflow as tf

In [20]:


with tf.Session() as sess:
    w1 = tf.constant([[1., 2.], [3., 4.]])
    w2 = tf.constant([[[[1., 2., 3.] for i in range(3)] for j in range(3)], [[[1., 2., 3.] for i in range(3)] for j in range(3)]])
#     w2= tf.split(w2, 2, 0)
#     w3 = tf.nn.softmax(w1, 1)
#     w1 = tf.split(w1, 2, 0)
#     lit = []
#     for i, j in zip(w1, w2):
#         i = tf.squeeze(i)
#         fb, fc = tf.split(j, 2, 3)
#         lit.append(i[0] * fb + i[1] * fc)
#     print(sess.run(w3))
#     print(sess.run(tf.concat(lit, 0)))
#     lit = []
#     for i, j in zip(w1, w2):
#         fb, fc = tf.split(j, 2, axis=3)
#         lit.append(i[0] * fb + i[1] * fc)
    offset = tf.slice(w2, [0, 0, 0, 0], [2, 3, 3, 2])
    mask = tf.slice(w2, [0, 0, 0, 2], [2, 3, 3, 1])
    print(sess.run(offset))
    print(sess.run(mask))

[[[[1. 2.]
   [1. 2.]
   [1. 2.]]

  [[1. 2.]
   [1. 2.]
   [1. 2.]]

  [[1. 2.]
   [1. 2.]
   [1. 2.]]]


 [[[1. 2.]
   [1. 2.]
   [1. 2.]]

  [[1. 2.]
   [1. 2.]
   [1. 2.]]

  [[1. 2.]
   [1. 2.]
   [1. 2.]]]]
[[[[3.]
   [3.]
   [3.]]

  [[3.]
   [3.]
   [3.]]

  [[3.]
   [3.]
   [3.]]]


 [[[3.]
   [3.]
   [3.]]

  [[3.]
   [3.]
   [3.]]

  [[3.]
   [3.]
   [3.]]]]


In [26]:
import tensorflow as tf
import sys
tf.sysconfig.get_include()

'/home/zzn/SANet_implementation-master/lib/python3.5/site-packages/tensorflow/include'

In [21]:
import tensorflow as tf
in_h, in_w = [int(i) for i in [11, 8]]
print(in_h, in_w)
feat_h, feat_w = [int(i) for i in [in_h, in_w]]
x, y = tf.meshgrid(tf.range(feat_w), tf.range(feat_h))
x, y = [tf.reshape(i, [1, *i.get_shape(), 1]) for i in [x, y]]  # shape [1, h, w, 1]
x, y = [tf.image.extract_image_patches(i, [1, 3, 3, 1], [1, 1, 1, 1], [1, 1, 1, 1], 'VALID') 
        for i in [x, y]] 
sess = tf.Session()
a, b = sess.run([x, y])
for i in [a, b]:
    print(i)

11 8
[[[[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2 0 1 2]
   [1 2 3 1 2 3 1 2 3]
   [2 3 4 2 3 4 2 3 4]
   [3 4 5 3 4 5 3 4 5]
   [4 5 6 4 5 6 4 5 6]
   [5 6 7 5 6 7 5 6 7]]

  [[0 1 2 0 1 2

In [1]:


inputs = tf.placeholder(tf.float32, [None, 224, 224, 3])
front_end, init_fn = ADCrowdNet.ADCrowdNet_model(inputs)
sess = tf.Session()
init_op = tf.global_variables_initializer()
sess.run(init_op)
init_fn(sess)

NameError: name 'tf' is not defined

In [3]:
tf.Graph().get_operations()

[]